# The name of our workflow
name: Build
# Trigger on every pull request
on: pull_request
push:
  branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build the app
        run: ./gradlew build
      - name: Run unit test
        run: ./gradlew myinfo:test
